name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        minikube start
        alias kubectl="minikube kubectl --"

    - name: Build Docker Images
      run: |
        eval $(minikube docker-env)
        docker build -t backend:latest ./backend
        docker build -t frontend:latest ./frontend

    - name: Create Namespace
      run: |
        kubectl create namespace my-namespace || echo "Namespace already exists"

    - name: Apply Kubernetes Resources
      run: |
        kubectl apply -f ./kubernetes/backend-deployment.yaml
        kubectl apply -f ./kubernetes/frontend-deployment.yaml
        kubectl apply -f ./kubernetes/nginx-deployment.yaml
        kubectl apply -f ./kubernetes/nginx-service.yaml

    - name: Expose Frontend
      run: |
        kubectl port-forward svc/nginx-service -n my-namespace 8080:80 &
        echo "Access Frontend at: http://localhost:8080"
